/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ObjData } from "../api/models/item";
import type { UniverseObjData } from "../api/models/universe";
import type { perms } from "../lib/perms";
import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Authoruniverse {
  id: Generated<number>;
  permission_level: number;
  universe_id: number;
  user_id: number;
}

export interface Boardnote {
  board_id: number;
  note_id: number;
}

export interface Comment {
  author_id: number | null;
  body: string | null;
  created_at: Date;
  id: Generated<number>;
  reply_to: number | null;
}

export interface Contact {
  accepted: boolean | null;
  accepting_user: number;
  requesting_user: number;
}

export interface Discussion {
  id: Generated<number>;
  title: string;
  universe_id: number;
}

export interface Eventorder {
  former: number;
  latter: number;
}

export interface Followeruniverse {
  is_following: boolean;
  universe_id: number;
  user_id: number;
}

export interface Image {
  data: Buffer;
  id: Generated<number>;
  mimetype: string;
  name: string;
  preview: Buffer | null;
}

export interface Item {
  author_id: number | null;
  created_at: Date;
  id: Generated<number>;
  item_type: string;
  last_updated_by: number | null;
  obj_data: ColumnType<ObjData, string, string>;
  parent_id: number | null;
  shortname: string;
  title: string;
  universe_id: number;
  updated_at: Date;
  vault_id: number | null;
}

export interface Itemcomment {
  comment_id: number;
  item_id: number;
}

export interface Itemembeddedchunks {
  chunk_id: string;
  content: string | null;
  hash: string;
  heading_path: string | null;
  id: Generated<number>;
  item_id: number;
  scope: string;
  token_count: number | null;
}

export interface Itemevent {
  abstime: number | null;
  event_title: string | null;
  id: Generated<number>;
  item_id: number;
}

export interface Itemimage {
  idx: number;
  image_id: number;
  item_id: number;
  label: string;
}

export interface Itemlink {
  from_item: number;
  href: string;
  to_item_short: string;
  to_universe_short: string;
}

export interface Itemnote {
  item_id: number;
  note_id: number;
}

export interface Itemnotification {
  is_enabled: boolean;
  item_id: number;
  user_id: number;
}

export interface Lineage {
  child_id: number;
  child_title: string | null;
  parent_id: number;
  parent_title: string | null;
}

export interface Map {
  height: number | null;
  id: Generated<number>;
  image_id: number | null;
  item_id: number;
  width: number | null;
}

export interface Maplocation {
  id: Generated<number>;
  item_id: number | null;
  map_id: number;
  title: string | null;
  x: number;
  y: number;
}

export interface Note {
  author_id: number;
  body: Json | null;
  created_at: Date;
  id: Generated<number>;
  is_public: boolean | null;
  title: string | null;
  updated_at: Date;
  uuid: string;
}

export interface Noteboard {
  id: Generated<number>;
  is_public: boolean | null;
  shortname: string;
  title: string;
  universe_id: number;
}

export interface Notetag {
  note_id: number;
  tag: string | null;
}

export interface Notificationsubscription {
  endpoint_hash: string;
  id: Generated<number>;
  push_endpoint: string;
  push_keys: Json;
  user_id: number;
}

export interface Notificationtype {
  is_enabled: boolean;
  notif_method: number;
  notif_type: string;
  user_id: number;
}

export interface OauthAccessToken {
  client_id: string;
  created_at: Date;
  expires_at: Date;
  resource: string | null;
  scope: string | null;
  token: string;
  user_id: number;
}

export interface OauthAuthorizationCode {
  client_id: string;
  code: string;
  code_challenge: string;
  created_at: Date;
  expires_at: Date;
  redirect_uri: string;
  resource: string | null;
  scope: string | null;
  user_id: number;
}

export interface OauthClient {
  client_id: string;
  client_name: string | null;
  client_secret: string | null;
  client_secret_expires_at: number | null;
  created_at: Date;
  grant_types: Json | null;
  metadata: Json | null;
  redirect_uris: Json;
  response_types: Json | null;
  scope: string | null;
  token_endpoint_auth_method: string | null;
}

export interface OauthRefreshToken {
  client_id: string;
  created_at: Date;
  expires_at: Date;
  scope: string | null;
  token: string;
  user_id: number;
}

export interface SchemaVersion {
  comment: string;
  time: Date | null;
  version: number | null;
}

export interface Sentemail {
  recipient: string;
  sent_at: Date;
  topic: string;
}

export interface Sentnotification {
  body: string | null;
  click_url: string | null;
  comment_id: number | null;
  dedup_key: string | null;
  icon_url: string | null;
  id: Generated<number>;
  is_read: Generated<boolean | null>;
  notif_type: string;
  sent_at: Date;
  title: string | null;
  user_id: number;
}

export interface Session {
  created_at: Date;
  hash: string;
  id: Generated<number>;
  user_id: number | null;
}

export interface Snooze {
  item_id: number;
  snoozed_at: Date;
  snoozed_by: number;
}

export interface Story {
  author_id: number | null;
  created_at: Date;
  drafts_public: boolean;
  id: Generated<number>;
  shortname: string;
  summary: string | null;
  title: string;
  universe_id: number;
  updated_at: Date;
}

export interface Storychapter {
  body: Json | null;
  chapter_number: number;
  created_at: Date;
  id: Generated<number>;
  is_published: Generated<boolean>;
  story_id: number;
  summary: string | null;
  title: string;
  updated_at: Date;
}

export interface Storychaptercomment {
  chapter_id: number;
  comment_id: number;
}

export interface Storyimage {
  image_id: number;
  story_id: number;
}

export interface Tag {
  item_id: number;
  tag: string | null;
}

export interface Threadcomment {
  comment_id: number;
  thread_id: number;
}

export interface Threadnotification {
  is_enabled: boolean;
  thread_id: number;
  user_id: number;
}

export interface Timelineitem {
  event_id: number;
  timeline_id: number;
}

export interface Universe {
  author_id: number | null;
  created_at: Date;
  discussion_enabled: boolean;
  discussion_open: boolean;
  id: Generated<number>;
  is_public: boolean;
  mcp_discussions_enabled: Generated<boolean>;
  mcp_items_enabled: Generated<boolean>;
  mcp_notes_enabled: Generated<boolean>;
  obj_data: ColumnType<UniverseObjData, string, string>;
  shortname: string;
  title: string;
  updated_at: Date;
}

export interface Universeaccessrequest {
  inviter_id: number | null;
  is_invite: Generated<boolean>;
  permission_level: perms;
  universe_id: number;
  user_id: number;
}

export interface Universenotification {
  is_enabled: boolean;
  universe_id: number;
  user_id: number;
}

export interface User {
  created_at: Date;
  custom_theme: Json | null;
  email: string;
  email_notifications: Generated<boolean | null>;
  id: Generated<number>;
  password: string;
  preferred_theme: string | null;
  salt: string;
  suspect: Generated<boolean | null>;
  updated_at: Date;
  username: string;
  verified: Generated<boolean | null>;
}

export interface Userdeleterequest {
  requested_at: Generated<Date | null>;
  user_id: number;
}

export interface Userimage {
  image_id: number;
  user_id: number;
}

export interface Usernamechange {
  changed_at: Date;
  changed_for: number;
  changed_from: string;
  changed_to: string;
}

export interface Userpasswordreset {
  expires_at: Date;
  reset_key: string;
  user_id: number;
}

export interface Userplan {
  plan: number;
  user_id: number;
}

export interface Usersponsoreduniverse {
  tier: number;
  universe_id: number;
  user_id: number;
}

export interface Userverification {
  user_id: number;
  verification_key: string | null;
}

export interface Vault {
  created_at: Date;
  id: Generated<number>;
  shortname: string;
  title: string;
  universe_id: number;
  updated_at: Date;
}

export interface Vaultauthor {
  id: Generated<number>;
  permission_level: number;
  user_id: number;
  vault_id: number;
}

export interface DB {
  authoruniverse: Authoruniverse;
  boardnote: Boardnote;
  comment: Comment;
  contact: Contact;
  discussion: Discussion;
  eventorder: Eventorder;
  followeruniverse: Followeruniverse;
  image: Image;
  item: Item;
  itemcomment: Itemcomment;
  itemembeddedchunks: Itemembeddedchunks;
  itemevent: Itemevent;
  itemimage: Itemimage;
  itemlink: Itemlink;
  itemnote: Itemnote;
  itemnotification: Itemnotification;
  lineage: Lineage;
  map: Map;
  maplocation: Maplocation;
  note: Note;
  noteboard: Noteboard;
  notetag: Notetag;
  notificationsubscription: Notificationsubscription;
  notificationtype: Notificationtype;
  oauth_access_token: OauthAccessToken;
  oauth_authorization_code: OauthAuthorizationCode;
  oauth_client: OauthClient;
  oauth_refresh_token: OauthRefreshToken;
  schema_version: SchemaVersion;
  sentemail: Sentemail;
  sentnotification: Sentnotification;
  session: Session;
  snooze: Snooze;
  story: Story;
  storychapter: Storychapter;
  storychaptercomment: Storychaptercomment;
  storyimage: Storyimage;
  tag: Tag;
  threadcomment: Threadcomment;
  threadnotification: Threadnotification;
  timelineitem: Timelineitem;
  universe: Universe;
  universeaccessrequest: Universeaccessrequest;
  universenotification: Universenotification;
  user: User;
  userdeleterequest: Userdeleterequest;
  userimage: Userimage;
  usernamechange: Usernamechange;
  userpasswordreset: Userpasswordreset;
  userplan: Userplan;
  usersponsoreduniverse: Usersponsoreduniverse;
  userverification: Userverification;
  vault: Vault;
  vaultauthor: Vaultauthor;
}
