name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: archiviumtest
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              break
            fi
            echo 'Waiting for MySQL...'
            sleep 1
          done

      - name: Start server
        run: |
          npm run build &
          nohup npm start &
          sleep 5
        env:
          PORT: 33004
          DOMAIN: dev.archivium.net
          ADDR_PREFIX: 
          DEV_MODE: true
          SENDGRID_API_KEY: 
          OPENAI_API_KEY: 
          WEB_PUSH_ENABLED: 

          ARCHIVIUM_DB_HOST: localhost
          ARCHIVIUM_DB_USER: testuser
          ARCHIVIUM_DB_PASSWORD: testpassword
          ARCHIVIUM_DB: archiviumtest

      - name: Setup database
        run: yes | npm run db:reset
        env:
          DEV_MODE: true
          ARCHIVIUM_DB_HOST: localhost
          ARCHIVIUM_DB_USER: testuser
          ARCHIVIUM_DB_PASSWORD: testpassword
          ARCHIVIUM_DB: archiviumtest

      - name: Run tests
        run: npm test

      - name: Show server logs
        if: failure()
        run: cat logs/current.log